# Generated by Django 5.0.4 on 2024-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('no_of_doors', models.IntegerField(max_length=2)),
                ('color', models.CharField(max_length=30)),
                ('engine_type', models.CharField(max_length=15)),
            ],
        ),
    ]
